# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 40, 41, 16))
        self.label.setObjectName("label")
        self.title_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.title_lineEdit.setGeometry(QtCore.QRect(70, 40, 131, 21))
        self.title_lineEdit.setObjectName("title_lineEdit")
        self.note_plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.note_plainTextEdit.setGeometry(QtCore.QRect(40, 100, 321, 121))
        self.note_plainTextEdit.setObjectName("note_plainTextEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 41, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(210, 240, 113, 32))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "title:"))
        self.label_2.setText(_translate("Dialog", "note:"))
        self.pushButton.setText(_translate("Dialog", "OK"))
